name: Doxygen

on:
  push:
    branches:
      - main  # Trigger the action on push events to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Create docs directory
        run: mkdir -p ${{ github.workspace }}/docs

      - name: Generate Doxygen
        run: |
          sed -i 's|@ROOT_DIR@|'"${{ github.workspace }}"'|g' Doxygen/Doxyfile
          doxygen Doxygen/Doxyfile

      - name: Print docs directory contents
        run: ls -l ${{ github.workspace }}/docs